#!/bin/bash
# 抛硬币脚本
# Author: Lucien-X
# Origin: https://www.v2ex.com/t/548388

# Define backspace char
BACKSPACE='\b\b'
# Loop animation for about 1s
i="0"
while [ $i -lt 24 ]
do
  for COIN in '🌝' '🌖' '🌗' '🌘' '🌚' '🌒' '🌓' '🌔'
  do
    echo -en "$BACKSPACE$COIN"
    sleep 0.0417; # Insure 24 fps (1/24 ≈ 0.0417)
    i=$[$i+1];
  done
done
# Roll the dice eventually
echo -en $BACKSPACE
if [[ $[ $RANDOM % 2 ] == 0 ]]
then
  echo -en "🌝\n"
else
  echo -en "🌚\n"
fi