#!/bin/bash
# 获取剪切板图片，上传到七牛云，并把图片地址输出到剪切板上。将整个截图到图床的过程简化为两个快捷键。
# usage: uimg (设置截图快捷键，保存图片到.cache/screenshot.jpg，再设置快捷键执行 uimg)
# author: adevjoe
# 依赖:
#   - qshell https://github.com/qiniu/qshell
#   - xclip 系统自带包管理安装

# 获取图片路径
IMG_PATH=$HOME/.cache/screenshot.jpg
IMG_NAME=$(date '+%s')$(cat /dev/urandom | head -n 10 | md5sum | head -c 10).jpg

# 上传
qshell fput img-bucket $IMG_NAME $IMG_PATH true

# 获取图片地址
url=https://$(qshell domains img-bucket|head -n 1)/$IMG_NAME

# 输出到剪切板
echo $url | xclip -selection clipboard

notify-send "图片地址已经保存到剪切板。"